version: "0.2.1"
Species:
  ensembl:
    vertebrate:
      release-109:
        url: https://ftp.ensembl.org/pub/release-109/species_EnsemblVertebrates.txt
      release-108:
        url: https://ftp.ensembl.org/pub/release-108/species_EnsemblVertebrates.txt
    name: Ensembl
    website: https://www.ensembl.org
Gene:
  ensembl:
    human:
      release-109:
        url: s3://bionty-assets/human_ensembl_release-109_Gene_lookup.parquet
    mouse:
      release-109:
        url: s3://bionty-assets/mouse_ensembl_release-109_Gene_lookup.parquet
    name: Ensembl
    website: https://www.ensembl.org
Protein:
  uniprot:
    human:
      2023-03:
        url: s3://bionty-assets/human_uniprot_2023-03_Protein_lookup.parquet
      2023-02:
        url: s3://bionty-assets/human_uniprot_2023-02_Protein_lookup.parquet
    mouse:
      2023-03:
        url: s3://bionty-assets/mouse_uniprot_2023-03_Protein_lookup.parquet
      2023-02:
        url: s3://bionty-assets/mouse_uniprot_2023-02_Protein_lookup.parquet
    name: Uniprot
    website: https://www.uniprot.org
CellMarker:
  cellmarker:
    human:
      2.0:
        url: s3://bionty-assets/human_cellmarker_2.0_CellMarker_lookup.parquet
    mouse:
      2.0:
        url: s3://bionty-assets/mouse_cellmarker_2.0_CellMarker_lookup.parquet
    name: CellMarker
    website: http://bio-bigdata.hrbmu.edu.cn/CellMarker
CellLine:
  clo:
    all:
      2022-03-21:
        url: https://data.bioontology.org/ontologies/CLO/submissions/65/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
        md5: ea58a1010b7e745702a8397a526b3a33
    name: Cell Line Ontology
    website: https://bioportal.bioontology.org/ontologies/CLO
CellType:
  cl:
    all:
      2023-04-20:
        url: http://purl.obolibrary.org/obo/cl/releases/2023-04-20/cl-base.owl
        md5: ""
      2023-02-15:
        url: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
        md5: 9331a6a029cb1863bd0584ab41508df7
      2022-08-16:
        url: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
        md5: d0655766574e63f3fe5ed56d3c030880
    name: Cell Ontology
    website: https://obophenotype.github.io/cell-ontology
Tissue:
  uberon:
    all:
      2023-04-19:
        url: http://purl.obolibrary.org/obo/uberon/releases/2023-04-19/uberon.owl
        md5: ""
      2023-02-14:
        url: http://purl.obolibrary.org/obo/uberon/releases/2023-02-14/uberon.owl
        md5: 3f94e22fae4cdde88a555c5cd59c47da
      2022-08-19:
        url: http://purl.obolibrary.org/obo/uberon/releases/2022-08-19/uberon.owl
        md5: c7c958a1ee48fdce146f2c1763eed27e
    name: Uberon multi-species anatomy ontology
    website: http://obophenotype.github.io/uberon
Disease:
  mondo:
    all:
      2023-04-04:
        url: http://purl.obolibrary.org/obo/mondo/releases/2023-04-04/mondo.owl
        md5: ""
      2023-02-06:
        url: http://purl.obolibrary.org/obo/mondo/releases/2023-02-06/mondo.owl
        md5: 2b7d479d4bd02a94eab47d1c9e64c5db
      2022-10-11:
        url: http://purl.obolibrary.org/obo/mondo/releases/2022-10-11/mondo.owl
        md5: 04b808d05c2c2e81430b20a0e87552bb
    name: Mondo Disease Ontology
    website: https://mondo.monarchinitiative.org
  doid:
    human:
      2023-03-31:
        url: http://purl.obolibrary.org/obo/doid/releases/2023-03-31/doid.obo
        md5: ""
      2023-01-30:
        url: http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo
        md5: 9f0c92ad2896dda82195e9226a06dc36
    name: Human Disease Ontology
    website: https://disease-ontology.org
ExperimentalFactor:
  efo:
    all:
      3.48.0:
        url: http://www.ebi.ac.uk/efo/releases/v3.48.0/efo.owl
        md5: 3367e9a9ae3dee9113024e5108c49091
    name: The Experimental Factor Ontology
    website: https://bioportal.bioontology.org/ontologies/EFO
Phenotype:
  hp:
    human:
      2023-06-17:
        url: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-06-17/hp.owl
        md5: ""
      2023-04-05:
        url: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-04-05/hp.owl
        md5: ""
      2023-01-27:
        url: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-01-27/hp.owl
        md5: ceeb3ada771908deef620d74cd8e6b0f
    name: Human Phenotype Ontology
    website: https://hpo.jax.org
  mp:
    mammalian:
      2023-05-31:
        url: https://github.com/mgijax/mammalian-phenotype-ontology/releases/download/v2023-05-31/mp.owl
        md5: ""
    name: Mammalian Phenotype Ontology
    website: https://github.com/mgijax/mammalian-phenotype-ontology
  zp:
    zebrafish:
      2022-12-17:
        url: https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/download/v2022-12-17/zp.owl
        md5: ""
    name: Zebrafish Phenotype Ontology
    website: https://github.com/obophenotype/zebrafish-phenotype-ontology
Pathway:
  go:
    all:
      2023-05-10:
        url: https://data.bioontology.org/ontologies/GO/submissions/1814/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
        md5: ""
    name: Gene Ontology
    website: http://geneontology.org
  pw:
    all:
      7.79:
        url: https://data.bioontology.org/ontologies/PW/submissions/109/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
        md5: 02e2337bb1ab7cc4332ef6acc4cbdfa6
    name: Pathway Ontology
    website: https://www.ebi.ac.uk/ols/ontologies/pw
BFXPipeline:
  lamin:
    all:
      1.0.0:
        url: s3://bionty-assets/bfxpipelines.json
        md5: ""
    name: Bioinformatics Pipeline
    website: https://lamin.ai
Drug:
  dron:
    all:
      2023-03-10:
        url: https://data.bioontology.org/ontologies/DRON/submissions/17/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
        md5: ""
    name: Drug Ontology
    website: https://bioportal.bioontology.org/ontologies/DRON
