name: Update Version URLs

on:
  push:
    branches:
      - "staging"
  pull_request:
    branches:
      - "staging"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        package: ["bionty", "lnschema-bionty"]
    timeout-minutes: 25

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout lndocs
        uses: actions/checkout@v3
        with:
          repository: laminlabs/lndocs
          ssh-key: ${{ secrets.READ_LNDOCS }}
          path: lndocs
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache nox
        uses: actions/cache@v3
        with:
          path: .nox
          key: nox-${{ runner.os }}
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Cache postgres
        id: cache-postgres
        uses: actions/cache@v3
        with:
          path: ~/postgres.tar
          key: cache-postgres-0
      - name: Cache postgres miss
        if: steps.cache-postgres.outputs.cache-hit != 'true'
        run: docker pull postgres:latest && docker image save postgres:latest --output ~/postgres.tar
      - name: Cache postgres use
        if: steps.cache-postgres.outputs.cache-hit == 'true'
        run: docker image load --input ~/postgres.tar

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U laminci
          pip install lamindb
          sudo apt-get -y install graphviz
          sudo apt-get install sqlite3-tools=3.37.2-2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      #      - name: Nox tests
      #        run: |
      #          nox -s "build(package='${{ matrix.package }}')"

      - name: Update version URLs
        run: echo "test" > test.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: "staging"
          commit-message: Update ontology URLs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: s3_ontologies_update
          delete-branch: true
          title: "Updating ontology URLs"
          add-paths: |
            test.md
